# MOVIES RECOMMENDER PROJECT

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
movies = pd.read_csv("movies_metadata.csv",low_memory=False)
credits = pd.read_csv("credits.csv")

In [33]:
pd.set_option('display.max_columns',None)

In [35]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [55]:
movies.shape

(12984, 24)

In [57]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [59]:
credits.shape

(12984, 3)

In [61]:
movies['id']=pd.to_numeric(movies['id'], errors='coerce')

In [63]:
movies = movies.merge(credits,on='id')

In [65]:
movies.shape

(12992, 26)

In [67]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,cast,crew
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [69]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

In [5]:
keywords = pd.read_csv("keywords.csv")

In [71]:
movies=movies.merge(keywords,on='id')

In [73]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,cast,crew,keywords
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [75]:
movies['original_language'].value_counts()

original_language
en    10643
fr      592
ja      313
it      239
de      209
es      172
cn      103
zh       99
sv       91
ko       63
ru       62
da       55
fi       44
pt       42
pl       33
fa       30
hi       26
cs       25
nl       25
he       17
no       15
th       15
hu       14
sr       10
el        9
ro        7
tr        7
bn        5
vi        4
bs        3
xx        3
ar        3
mn        2
ab        2
is        2
bm        2
nb        2
sk        2
ca        2
bo        2
sh        2
wo        2
mk        1
ps        1
eo        1
ka        1
cy        1
zu        1
uk        1
af        1
la        1
et        1
Name: count, dtype: int64

In [77]:
movies.isnull().sum()

adult                        0
belongs_to_collection    11257
budget                       0
genres                       0
homepage                 11714
id                           0
imdb_id                      1
original_language            0
original_title               0
overview                    35
popularity                   0
poster_path                 33
production_companies         0
production_countries         0
release_date                 5
revenue                      0
runtime                      6
spoken_languages             0
status                       9
tagline                   4416
title                        0
video                        0
vote_average                 0
vote_count                   0
cast                         0
crew                         0
keywords                     0
dtype: int64

In [79]:
movies = movies[['genres','id','original_title','overview','popularity','release_date','cast','crew','keywords']]

In [81]:
movies.head()

,genres,id,original_title,overview,popularity,release_date,cast,crew,keywords
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,1995-02-10,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [83]:
movies['release_year'] = pd.to_datetime(movies['release_date'], errors='coerce').dt.year

In [85]:
movies.head()

,genres,id,original_title,overview,popularity,release_date,cast,crew,keywords,release_year
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",1995.0
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",1995.0
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",1995.0
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",1995.0
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,1995-02-10,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",1995.0

In [87]:
movies.drop('release_date',axis=1,inplace=True)

In [89]:
movies.head()

,genres,id,original_title,overview,popularity,cast,crew,keywords,release_year
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",1995.0
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",1995.0
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",1995.0
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",1995.0
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",1995.0

In [91]:
movies.isnull().sum()

genres             0
id                 0
original_title     0
overview          35
popularity         0
cast               0
crew               0
keywords           0
release_year       5
dtype: int64

In [93]:
movies['overview']=movies['overview'].fillna('')

In [95]:
movies.dropna(inplace=True)

In [97]:
movies.shape

(13003, 9)

In [99]:
movies.duplicated().sum()

27

In [101]:
movies.drop_duplicates(subset='id', inplace=True)

In [103]:
movies.head()

,genres,id,original_title,overview,popularity,cast,crew,keywords,release_year
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",1995.0
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",1995.0
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",1995.0
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",1995.0
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",1995.0

In [105]:
movies.shape

(12975, 9)

In [107]:
movies['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [109]:
import ast
def clean(x):
    s=""
    for i in ast.literal_eval(x):
        s+=i['name'].replace(" ","") + " "
    return s

In [111]:
clean("[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family hyh'}]")

'Animation Comedy Familyhyh '

In [113]:
movies['genres'] = movies['genres'].apply(clean)

In [115]:
movies['keywords'][0]

"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]"

In [117]:
movies['keywords'] = movies['keywords'].apply(clean)

In [119]:
movies.head()

,genres,id,original_title,overview,popularity,cast,crew,keywords,release_year
0,Animation Comedy Family,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",jealousy toy boy friendship friends rivalry bo...,1995.0
1,Adventure Fantasy Family,8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",boardgame disappearance basedonchildren'sbook ...,1995.0
2,Romance Comedy,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",fishing bestfriend duringcreditsstinger oldmen,1995.0
3,Comedy Drama Romance,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",basedonnovel interracialrelationship singlemot...,1995.0
4,Comedy,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",baby midlifecrisis confidence aging daughter m...,1995.0

In [121]:
movies['cast'][0]

"[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]"

In [123]:
# for extracting only top three members.
def clean_cast(x):
    s=""
    count=0
    try:
        cast_list = ast.literal_eval(x)
        for i in cast_list:
            if count < 3:
                s += i['name'].replace(" ","") + " "
                count += 1
            else:
                break
    except (ValueError, SyntaxError, TypeError):
        # Handle NaN or malformed data
        return ""
    return s.strip()

In [125]:
movies['cast'] = movies['cast'].apply(clean_cast)

In [127]:
movies['crew'][0]

'[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'Alec Sokolow\', \'profile_path\': \'/v79vlRYi94BZUQnkkyznbGUZLjT.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f67\', \'department\': \'Production\', \'gender\': 1, \'id\': 12894, \'job\': \'Producer\', \'name\': \'Bonnie Arnold\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f6d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12895, \'job\': \'Executive Producer\', \'name\': \'Ed Catmull\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f73\', \'department\': \'Production\', \'gender\': 2, \'id\': 12896, \'job\': \'Producer\', \'name\': \'Ralph Guggenheim\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f79\', \'department\': \'Production\', \'gender\': 2, \'id\': 12897, \'job\': \'Executive Producer\', \'name\': \'Steve Jobs\', \'profile_path\': \'/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f8b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 8, \'job\': \'Editor\', \'name\': \'Lee Unkrich\', \'profile_path\': \'/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f91\', \'department\': \'Art\', \'gender\': 2, \'id\': 7883, \'job\': \'Art Direction\', \'name\': \'Ralph Eggleston\', \'profile_path\': \'/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg\'}, {\'credit_id\': \'598331bf925141421201044b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 1168870, \'job\': \'Editor\', \'name\': \'Robert Gordon\', \'profile_path\': None}, {\'credit_id\': \'5892168cc3a36809660095f9\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1552883, \'job\': \'Foley Editor\', \'name\': \'Mary Helen Leasman\', \'profile_path\': None}, {\'credit_id\': \'5531824d9251415289000945\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1453514, \'job\': \'Animation\', \'name\': \'Kim Blanchette\', \'profile_path\': None}, {\'credit_id\': \'589215969251412dcb009bf6\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414182, \'job\': \'ADR Editor\', \'name\': \'Marilyn McCoppen\', \'profile_path\': None}, {\'credit_id\': \'589217099251412dc500a018\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Orchestrator\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5693e6b29251417b0e0000e3\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1429549, \'job\': \'Color Timer\', \'name\': \'Dale E. Grahn\', \'profile_path\': None}, {\'credit_id\': \'572e2522c3a36869e6001a9c\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7949, \'job\': \'CG Painter\', \'name\': \'Robin Cooper\', \'profile_path\': None}, {\'credit_id\': \'574f12309251415ca1000012\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7879, \'job\': \'Original Story\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'574f1240c3a3682e7300001c\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12890, \'job\': \'Original Story\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'574f12519251415c92000015\', \'department\': \'Writing\', \'gender\': 0, \'id\': 7911, \'job\': \'Original Story\', \'name\': \'Joe Ranft\', \'profile_path\': \'/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'credit_id\': \'574f12cec3a3682e82000022\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1629419, \'job\': \'Post Production Supervisor\', \'name\': \'Patsy Bouge\', \'profile_path\': None}, {\'credit_id\': \'574f14f19251415ca1000082\', \'department\': \'Art\', \'gender\': 0, \'id\': 7961, \'job\': \'Sculptor\', \'name\': \'Norm DeCarlo\', \'profile_path\': None}, {\'credit_id\': \'5751ae4bc3a3683772002b7f\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 12905, \'job\': \'Animation Director\', \'name\': \'Ash Brannon\', \'profile_path\': \'/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg\'}, {\'credit_id\': \'5891edbe9251412dc5007cd6\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Music\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'589213d39251412dc8009832\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748707, \'job\': \'Layout\', \'name\': \'Roman Figun\', \'profile_path\': None}, {\'credit_id\': \'5892173dc3a3680968009351\', \'department\': \'Sound\', \'gender\': 2, \'id\': 4949, \'job\': \'Orchestrator\', \'name\': \'Don Davis\', \'profile_path\': None}, {\'credit_id\': \'589217cec3a3686b0a0052ba\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1372885, \'job\': \'Music Editor\', \'name\': \'James Flamberg\', \'profile_path\': None}, {\'credit_id\': \'58921831c3a3686348004a64\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1739962, \'job\': \'Negative Cutter\', \'name\': \'Mary Beth Smith\', \'profile_path\': None}, {\'credit_id\': \'58921838c3a36809700096c0\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748513, \'job\': \'Negative Cutter\', \'name\': \'Rick Mackay\', \'profile_path\': None}, {\'credit_id\': \'589218429251412dd1009d1b\', \'department\': \'Art\', \'gender\': 0, \'id\': 1458006, \'job\': \'Title Designer\', \'name\': \'Susan Bradley\', \'profile_path\': None}, {\'credit_id\': \'5891ed99c3a3680966007670\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1748557, \'job\': \'Supervising Technical Director\', \'name\': \'William Reeves\', \'profile_path\': None}, {\'credit_id\': \'5891edcec3a3686b0a002eb2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Songs\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5891edf9c3a36809700075e6\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Original Story\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58920f0b9251412dd7009104\', \'department\': \'Crew\', \'gender\': 2, \'id\': 12890, \'job\': \'Supervising Animator\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'58920f1fc3a3680977009021\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Designer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'58920f389251412dd700912d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12909, \'job\': \'Production Supervisor\', \'name\': \'Karen Robert Jackson\', \'profile_path\': None}, {\'credit_id\': \'58920fbd9251412dcb00969c\', \'department\': \'Crew\', \'gender\': 0, \'id\': 953331, \'job\': \'Executive Music Producer\', \'name\': \'Chris Montan\', \'profile_path\': None}, {\'credit_id\': \'589210069251412dd7009219\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7893, \'job\': \'Animation Director\', \'name\': \'Rich Quade\', \'profile_path\': None}, {\'credit_id\': \'589210329251412dcd00943b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8025, \'job\': \'Animation\', \'name\': \'Michael Berenstein\', \'profile_path\': None}, {\'credit_id\': \'5892103bc3a368096a009180\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 78009, \'job\': \'Animation\', \'name\': \'Colin Brady\', \'profile_path\': None}, {\'credit_id\': \'5892105dc3a3680968008db2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748682, \'job\': \'Animation\', \'name\': \'Davey Crockett Feiten\', \'profile_path\': None}, {\'credit_id\': \'589210669251412dcd009466\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454030, \'job\': \'Animation\', \'name\': \'Angie Glocka\', \'profile_path\': None}, {\'credit_id\': \'5892107c9251412dd1009613\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748683, \'job\': \'Animation\', \'name\': \'Rex Grignon\', \'profile_path\': None}, {\'credit_id\': \'5892108ac3a3680973008d3f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748684, \'job\': \'Animation\', \'name\': \'Tom K. Gurney\', \'profile_path\': None}, {\'credit_id\': \'58921093c3a3686348004477\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 8029, \'job\': \'Animation\', \'name\': \'Jimmy Hayward\', \'profile_path\': \'/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg\'}, {\'credit_id\': \'5892109b9251412dcd0094b0\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1426773, \'job\': \'Animation\', \'name\': \'Hal T. Hickel\', \'profile_path\': None}, {\'credit_id\': \'589210a29251412dc5009a29\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8035, \'job\': \'Animation\', \'name\': \'Karen Kiser\', \'profile_path\': None}, {\'credit_id\': \'589210ccc3a3680977009191\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748688, \'job\': \'Animation\', \'name\': \'Anthony B. LaMolinara\', \'profile_path\': None}, {\'credit_id\': \'589210d7c3a3686b0a004c1f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 587314, \'job\': \'Animation\', \'name\': \'Guionne Leroy\', \'profile_path\': None}, {\'credit_id\': \'589210e1c3a36809770091a7\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Animation\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'589210ee9251412dc200978a\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748689, \'job\': \'Animation\', \'name\': \'Les Major\', \'profile_path\': None}, {\'credit_id\': \'589210fa9251412dc8009595\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7892, \'job\': \'Animation\', \'name\': \'Glenn McQueen\', \'profile_path\': None}, {\'credit_id\': \'589211029251412dc8009598\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 555795, \'job\': \'Animation\', \'name\': \'Mark Oftedal\', \'profile_path\': None}, {\'credit_id\': \'5892110b9251412dc800959d\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7882, \'job\': \'Animation\', \'name\': \'Jeff Pidgeon\', \'profile_path\': \'/yLddkg5HcgbJg00cS13GVBnP0HY.jpg\'}, {\'credit_id\': \'58921113c3a36863480044e4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8017, \'job\': \'Animation\', \'name\': \'Jeff Pratt\', \'profile_path\': None}, {\'credit_id\': \'5892111c9251412dcb0097e9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1184140, \'job\': \'Animation\', \'name\': \'Steve Rabatich\', \'profile_path\': None}, {\'credit_id\': \'58921123c3a36809700090f6\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8049, \'job\': \'Animation\', \'name\': \'Roger Rose\', \'profile_path\': None}, {\'credit_id\': \'5892112b9251412dcb0097fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1509559, \'job\': \'Animation\', \'name\': \'Steve Segal\', \'profile_path\': None}, {\'credit_id\': \'589211349251412dc80095c3\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748691, \'job\': \'Animation\', \'name\': \'Doug Sheppeck\', \'profile_path\': None}, {\'credit_id\': \'5892113cc3a3680970009106\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8050, \'job\': \'Animation\', \'name\': \'Alan Sperling\', \'profile_path\': None}, {\'credit_id\': \'58921148c3a3686b0a004c99\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8010, \'job\': \'Animation\', \'name\': \'Doug Sweetland\', \'profile_path\': None}, {\'credit_id\': \'58921150c3a3680966009125\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8044, \'job\': \'Animation\', \'name\': \'David Tart\', \'profile_path\': None}, {\'credit_id\': \'589211629251412dc5009b00\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454034, \'job\': \'Animation\', \'name\': \'Ken Willard\', \'profile_path\': None}, {\'credit_id\': \'589211c1c3a3686b0a004d28\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7887, \'job\': \'Visual Effects Supervisor\', \'name\': \'Thomas Porter\', \'profile_path\': None}, {\'credit_id\': \'589211d4c3a3680968008ed9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1406878, \'job\': \'Visual Effects\', \'name\': \'Mark Thomas Henne\', \'profile_path\': None}, {\'credit_id\': \'589211f59251412dd4008e65\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748698, \'job\': \'Visual Effects\', \'name\': \'Oren Jacob\', \'profile_path\': None}, {\'credit_id\': \'58921242c3a368096a00939b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748699, \'job\': \'Visual Effects\', \'name\': \'Darwyn Peachey\', \'profile_path\': None}, {\'credit_id\': \'5892124b9251412dc5009bd2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748701, \'job\': \'Visual Effects\', \'name\': \'Mitch Prater\', \'profile_path\': None}, {\'credit_id\': \'58921264c3a3686b0a004dbf\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748703, \'job\': \'Visual Effects\', \'name\': \'Brian M. Rosen\', \'profile_path\': None}, {\'credit_id\': \'589212709251412dcd009676\', \'department\': \'Lighting\', \'gender\': 1, \'id\': 12912, \'job\': \'Lighting Supervisor\', \'name\': \'Sharon Calahan\', \'profile_path\': None}, {\'credit_id\': \'5892127fc3a3686b0a004de5\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 7899, \'job\': \'Lighting Supervisor\', \'name\': \'Galyn Susman\', \'profile_path\': None}, {\'credit_id\': \'589212cdc3a3680970009268\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'CG Painter\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892130f9251412dc8009791\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748705, \'job\': \'Sculptor\', \'name\': \'Shelley Daniels Lekven\', \'profile_path\': None}, {\'credit_id\': \'5892131c9251412dd4008f4c\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7889, \'job\': \'Character Designer\', \'name\': \'Bob Pauley\', \'profile_path\': None}, {\'credit_id\': \'589213249251412dd100987b\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Character Designer\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'5892132b9251412dc80097b1\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7, \'job\': \'Character Designer\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58921332c3a368634800467b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'Character Designer\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892135f9251412dd4008f90\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748706, \'job\': \'Character Designer\', \'name\': \'Steve Johnson\', \'profile_path\': None}, {\'credit_id\': \'58921384c3a3680973008fd4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1176752, \'job\': \'Character Designer\', \'name\': \'Dan Haskett\', \'profile_path\': None}, {\'credit_id\': \'5892138e9251412dc20099fc\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1088034, \'job\': \'Character Designer\', \'name\': \'Tom Holloway\', \'profile_path\': \'/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg\'}, {\'credit_id\': \'58921395c3a368097700942f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1447465, \'job\': \'Character Designer\', \'name\': \'Jean Gillmore\', \'profile_path\': None}, {\'credit_id\': \'589213e2c3a3680973009026\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748709, \'job\': \'Layout\', \'name\': \'Desirée Mourad\', \'profile_path\': None}, {\'credit_id\': \'589214099251412dc5009d57\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748710, \'job\': \'Set Dresser\', \'name\': "Kelly O\'Connell", \'profile_path\': None}, {\'credit_id\': \'58921411c3a3686b0a004f70\', \'department\': \'Art\', \'gender\': 0, \'id\': 1443471, \'job\': \'Set Dresser\', \'name\': \'Sonoko Konishi\', \'profile_path\': None}, {\'credit_id\': \'58921434c3a368096a00956e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748711, \'job\': \'Set Dresser\', \'name\': \'Ann M. Rockwell\', \'profile_path\': None}, {\'credit_id\': \'5892144ac3a36809680090de\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748712, \'job\': \'Editorial Manager\', \'name\': \'Julie M. McDonald\', \'profile_path\': None}, {\'credit_id\': \'58921479c3a368096800910f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1589729, \'job\': \'Assistant Editor\', \'name\': \'Robin Lee\', \'profile_path\': None}, {\'credit_id\': \'5892148b9251412dd10099cc\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748716, \'job\': \'Assistant Editor\', \'name\': \'Tom Freeman\', \'profile_path\': None}, {\'credit_id\': \'589214959251412dcb009b1f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748717, \'job\': \'Assistant Editor\', \'name\': \'Ada Cochavi\', \'profile_path\': None}, {\'credit_id\': \'5892149ec3a3686348004798\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1336438, \'job\': \'Assistant Editor\', \'name\': \'Dana Mulligan\', \'profile_path\': None}, {\'credit_id\': \'589214adc3a368096a0095db\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748718, \'job\': \'Editorial Coordinator\', \'name\': \'Deirdre Morrison\', \'profile_path\': None}, {\'credit_id\': \'589214c7c3a368097700952b\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748719, \'job\': \'Production Coordinator\', \'name\': \'Lori Lombardo\', \'profile_path\': None}, {\'credit_id\': \'589214cec3a368096a009603\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748720, \'job\': \'Production Coordinator\', \'name\': \'Ellen Devine\', \'profile_path\': None}, {\'credit_id\': \'589214e39251412dc8009904\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1468014, \'job\': \'Unit Publicist\', \'name\': \'Lauren Beth Strogoff\', \'profile_path\': None}, {\'credit_id\': \'58921544c3a3686b0a00507d\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'5892154c9251412dd1009a56\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1425978, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Summers\', \'profile_path\': None}, {\'credit_id\': \'58921555c3a36809680091bd\', \'department\': \'Sound\', \'gender\': 2, \'id\': 8276, \'job\': \'Supervising Sound Editor\', \'name\': \'Tim Holland\', \'profile_path\': None}, {\'credit_id\': \'589215c39251412dcb009c12\', \'department\': \'Sound\', \'gender\': 0, \'id\': 7069, \'job\': \'Sound Effects Editor\', \'name\': \'Pat Jackson\', \'profile_path\': None}, {\'credit_id\': \'58921698c3a368096a009788\', \'department\': \'Crew\', \'gender\': 2, \'id\': 15894, \'job\': \'Sound Design Assistant\', \'name\': \'Tom Myers\', \'profile_path\': None}, {\'credit_id\': \'589216a89251412dc2009ca4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414177, \'job\': \'Assistant Sound Editor\', \'name\': \'J.R. 

In [129]:
def clean_crew(x):
    s=""
    for i in ast.literal_eval(x):
        if i['job']=='Director':
            s+=i['name'].replace(" ","") + " "
            break
    return s

In [131]:
movies['crew'] = movies['crew'].apply(clean_crew)

In [133]:
movies.head()

,genres,id,original_title,overview,popularity,cast,crew,keywords,release_year
0,Animation Comedy Family,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,TomHanks TimAllen DonRickles,JohnLasseter,jealousy toy boy friendship friends rivalry bo...,1995.0
1,Adventure Fantasy Family,8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,RobinWilliams JonathanHyde KirstenDunst,JoeJohnston,boardgame disappearance basedonchildren'sbook ...,1995.0
2,Romance Comedy,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,WalterMatthau JackLemmon Ann-Margret,HowardDeutch,fishing bestfriend duringcreditsstinger oldmen,1995.0
3,Comedy Drama Romance,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,WhitneyHouston AngelaBassett LorettaDevine,ForestWhitaker,basedonnovel interracialrelationship singlemot...,1995.0
4,Comedy,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,SteveMartin DianeKeaton MartinShort,CharlesShyer,baby midlifecrisis confidence aging daughter m...,1995.0

In [135]:
movies['combined_features']=(
    movies['overview'] + ' ' +
    movies['genres'] +
    movies['keywords'] +
    movies['cast'] + ' ' +
    movies['crew']
)

In [137]:
movies.head()

,genres,id,original_title,overview,popularity,cast,crew,keywords,release_year,combined_features
0,Animation Comedy Family,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,TomHanks TimAllen DonRickles,JohnLasseter,jealousy toy boy friendship friends rivalry bo...,1995.0,"Led by Woody, Andy's toys live happily in his ..."
1,Adventure Fantasy Family,8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,RobinWilliams JonathanHyde KirstenDunst,JoeJohnston,boardgame disappearance basedonchildren'sbook ...,1995.0,When siblings Judy and Peter discover an encha...
2,Romance Comedy,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,WalterMatthau JackLemmon Ann-Margret,HowardDeutch,fishing bestfriend duringcreditsstinger oldmen,1995.0,A family wedding reignites the ancient feud be...
3,Comedy Drama Romance,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,WhitneyHouston AngelaBassett LorettaDevine,ForestWhitaker,basedonnovel interracialrelationship singlemot...,1995.0,"Cheated on, mistreated and stepped on, the wom..."
4,Comedy,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,SteveMartin DianeKeaton MartinShort,CharlesShyer,baby midlifecrisis confidence aging daughter m...,1995.0,Just when George Banks has recovered from his ...

In [139]:
df = movies[['id','original_title','popularity','release_year','combined_features']]

In [141]:
df.head()

,id,original_title,popularity,release_year,combined_features
0,862,Toy Story,21.946943,1995.0,"Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,17.015539,1995.0,When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,11.7129,1995.0,A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,3.859495,1995.0,"Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,8.387519,1995.0,Just when George Banks has recovered from his ...

In [143]:
df['combined_features'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family jealousy toy boy friendship friends rivalry boynextdoor newtoy toycomestolife TomHanks TimAllen DonRickles JohnLasseter "

In [145]:
df['combined_features'] = df['combined_features'].apply(lambda x:x.lower())

C:\Users\chait\AppData\Local\Temp\ipykernel_27640\3438055858.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['combined_features'] = df['combined_features'].apply(lambda x:x.lower())

In [147]:
df.head()

,id,original_title,popularity,release_year,combined_features
0,862,Toy Story,21.946943,1995.0,"led by woody, andy's toys live happily in his ..."
1,8844,Jumanji,17.015539,1995.0,when siblings judy and peter discover an encha...
2,15602,Grumpier Old Men,11.7129,1995.0,a family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,3.859495,1995.0,"cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,8.387519,1995.0,just when george banks has recovered from his ...

In [149]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import string

In [151]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    if isinstance(text, str):
        text = text.lower()
        text = text.translate(str.maketrans('', '', string.punctuation))
        words = word_tokenize(text)
        words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
        return ' '.join(words)
    else:
        return ''

In [153]:
df['combined_features'] = df['combined_features'].apply(preprocess_text)

C:\Users\chait\AppData\Local\Temp\ipykernel_27640\296262699.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['combined_features'] = df['combined_features'].apply(preprocess_text)

In [155]:
df.head()

,id,original_title,popularity,release_year,combined_features
0,862,Toy Story,21.946943,1995.0,led woody andys toy live happily room andys bi...
1,8844,Jumanji,17.015539,1995.0,sibling judy peter discover enchanted board ga...
2,15602,Grumpier Old Men,11.7129,1995.0,family wedding reignites ancient feud nextdoor...
3,31357,Waiting to Exhale,3.859495,1995.0,cheated mistreated stepped woman holding breat...
4,11862,Father of the Bride Part II,8.387519,1995.0,george bank recovered daughter wedding receive...

In [157]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [159]:
tfidf = TfidfVectorizer(max_features=10000,stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined_features'])

In [161]:
tfidf_matrix.shape

(12975, 10000)

In [163]:
from sklearn.metrics.pairwise import cosine_similarity

In [165]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [167]:
cosine_sim.shape

(12975, 12975)

In [169]:
indices = pd.Series(df.index, index=df['original_title']).drop_duplicates()

In [171]:
cosine_sim

array([[1.        , 0.02039052, 0.00637552, ..., 0.        , 0.        ,
        0.00783346],
       [0.02039052, 1.        , 0.02400465, ..., 0.02556567, 0.        ,
        0.05227966],
       [0.00637552, 0.02400465, 1.        , ..., 0.02640464, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02556567, 0.02640464, ..., 1.        , 0.        ,
        0.03487568],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.03405181],
       [0.00783346, 0.05227966, 0.        , ..., 0.03487568, 0.03405181,
        1.        ]])

In [193]:
def recommend(movie):
    idx = indices[movie]
    sim_score = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_score, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    for i in movie_indices:
        print(df["original_title"].iloc[i])
    return

In [195]:
(recommend("Waiting to Exhale"))

Bian zou bian chang
Robin and Marian
Gertrud
Phffft!
A Taste of Honey
Fever
Celebrity
Hero
À tout de suite
What's Love Got to Do with It

In [177]:
import pickle

In [179]:
pickle.dump(cosine_sim, open('similarity.pkl', 'wb'))

In [197]:
pickle.dump(df,open('movies.pkl','wb'))